package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "test")
public class Student implements java.io.Serializable {

	private int sid;
	private String sname;

	public Student() {
	}

	public Student(int sid) {
		this.sid = sid;
	}

	public Student(int sid, String sname) {
		this.sid = sid;
		this.sname = sname;
	}

	@Id
	@Column(name = "sid", unique = true, nullable = false)
	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	@Column(name = "sname", length = 45)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
